//! Fixture-driven validation tests. Each case under
//! `tests/fixtures/validation/<CASE>/` carries its own `mandate.yaml` and
//! `test.rs`, using the shared [`fake_virtual_machine`] helpers to build an
//! in-memory repository and check the rendered report against expectations.
//! The `#[path]` module declaration for each case is generated by
//! `build.rs` from the directories present at build time, so a case is
//! registered simply by existing.

mod fake_virtual_machine;

include!(concat!(env!("OUT_DIR"), "/validation_cases.rs"));

/// Guards against the generated case list going stale: Cargo's own
/// directory-change detection (`cargo:rerun-if-changed`) can miss an empty
/// new directory or a deleted one, so `build.rs`'s output can disagree with
/// what's actually on disk without the build script rerunning to catch it.
#[test]
fn discovered_cases_match_directories_on_disk() {
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/validation");

    let mut on_disk: Vec<String> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read {dir}: {e}"))
        .filter_map(|entry| entry.ok())
        .filter(|entry| entry.path().is_dir())
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .collect();
    on_disk.sort();

    let mut discovered: Vec<String> = DISCOVERED_CASES.iter().map(|s| s.to_string()).collect();
    discovered.sort();

    let missing_from_generated: Vec<&String> =
        on_disk.iter().filter(|d| !discovered.contains(d)).collect();
    let missing_on_disk: Vec<&String> =
        discovered.iter().filter(|d| !on_disk.contains(d)).collect();

    assert!(
        missing_from_generated.is_empty() && missing_on_disk.is_empty(),
        "directories on disk but not discovered: {missing_from_generated:?}; \
         discovered but no longer on disk: {missing_on_disk:?}; \
         the generated case list is stale; run `cargo clean -p mandate` or touch build.rs and rebuild"
    );
}
